INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'black', 0,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'brown', 5844766,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'dark brown', 3875595,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'light brown', 6700322,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'grey', 7696224,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'white', 15132390,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'blue', 152522,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'yellow', 13816322,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'orange', 14386178,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'red', 11152171,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'green', 95815,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'pink', 16672691,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'purple', 6569585,'He has Name beard');
INSERT INTO beard_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'gold', 11569973,'He has Name beard');
