INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'black', 0,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'black', 0,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'brown', 5844766,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'brown', 5844766,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'dark brown', 3875595,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'dark brown', 3875595,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'light brown', 6700322,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'light brown', 6700322,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'grey', 7696224,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'grey', 7696224,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'white', 15132390,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'white', 15132390,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'blue', 152522,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'blue', 152522,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'yellow', 13816322,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'yellow', 13816322,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'orange', 14386178,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'orange', 14386178,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'red', 11152171,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'red', 11152171,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'green', 95815,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'green', 95815,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'pink', 16672691,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'pink', 16672691,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'purple', 6569585,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'purple', 6569585,'She has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'gold', 11569973,'He has Name brow');
INSERT INTO brow_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'gold', 11569973,'She has Name brow');