INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'does not wear glasses', -1,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'does not wear glasses', -1,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears a monocle', 2451,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears a monocle', 2451,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears normal glasses', 2388,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears normal glasses', 2388,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears brown glasses', 2391,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears brown glasses', 2391,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears leopard glasses', 2390,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears leopard glasses', 2390,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears green glasses', 2392,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears green glasses', 2392,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears blue glasses', 2393,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears blue glasses', 2393,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears pointed glasses', 2404,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears pointed glasses', 2404,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears pointed white glasses', 2408,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears pointed white glasses', 2408,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears pointed leopard glasses', 2407,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears pointed leopard glasses', 2407,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears round glasses', 2374,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears round glasses', 2374,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears round silver glasses', 2371,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears round silver glasses', 2371,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears round gold glasses', 1370,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears round gold glasses', 1370,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears square glasses', 1459,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears square glasses', 1459,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears square white glasses', 2457,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears square white glasses', 2457,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears square silver glasses', 2458,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears square silver glasses', 2458,'She Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (1, 'wears square gold glasses', 2455,'He Name');
INSERT INTO glasses(gender_id, name, value, idiomatic_answer) VALUES (2, 'wears square gold glasses', 2455,'She Name');