INSERT INTO hair(gender_id, name, value) VALUES (1, 'has short straight hair', 1670);
INSERT INTO hair(gender_id, name, value) VALUES (2, 'has short straight hair', 1311);
INSERT INTO hair(gender_id, name, value) VALUES (1, 'has straight hair', 1341);
INSERT INTO hair(gender_id, name, value) VALUES (2, 'has straight hair', 1314);
INSERT INTO hair(gender_id, name, value) VALUES (1, 'has short curly hair', 1729);
INSERT INTO hair(gender_id, name, value) VALUES (2, 'has short curly hair', 1326);
INSERT INTO hair(gender_id, name, value) VALUES (1, 'has curly hair', 1645);
INSERT INTO hair(gender_id, name, value) VALUES (2, 'has curly hair', 1332);
INSERT INTO hair(gender_id, name, value) VALUES (1, 'puts hair in a ponytail', 1700);
INSERT INTO hair(gender_id, name, value) VALUES (2, 'puts hair in a ponytail', 1705);
INSERT INTO hair(gender_id, name, value) VALUES (1, 'has comb-over hair', 1328);
INSERT INTO hair(gender_id, name, value) VALUES (2, 'has comb-over hair', 1328);
INSERT INTO hair(gender_id, name, value) VALUES (1, 'has short wavy hair', 1658);
INSERT INTO hair(gender_id, name, value) VALUES (2, 'has short wavy hair', 1329);
INSERT INTO hair(gender_id, name, value) VALUES (1, 'has wavy hair', 1338);
INSERT INTO hair(gender_id, name, value) VALUES (2, 'has wavy hair', 1321);
INSERT INTO hair(gender_id, name, value) VALUES (1, 'puts hair in pigtails', 1714);
INSERT INTO hair(gender_id, name, value) VALUES (2, 'puts hair in pigtails', 1715);
INSERT INTO hair(gender_id, name, value) VALUES (1, 'is bald', 2290);
INSERT INTO hair(gender_id, name, value) VALUES (2, 'is bald', 2290);
