INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has short straight hair', 1670, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has short straight hair', 1311, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has straight hair', 1341, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has straight hair', 1314, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has short curly hair', 1729, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has short curly hair', 1326, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has curly hair', 1645, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has curly hair', 1332, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'puts hair in a ponytail', 1700, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'puts hair in a ponytail', 1705, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has comb-over hair', 1328, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has comb-over hair', 1328, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has short wavy hair', 1658, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has short wavy hair', 1329, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has wavy hair', 1338, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has wavy hair', 1321, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'puts hair in pigtails', 1714, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'puts hair in pigtails', 1715, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'is bald', 2290, 'he Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'is bald', 2290, 'he Name');
