INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has short straight hair', 1670, 'He Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has short straight hair', 1311, 'She Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has straight hair', 1341, 'He Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has straight hair', 1314, 'She Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has short curly hair', 1729, 'He Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has short curly hair', 1326, 'She Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has curly hair', 1645, 'He Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has curly hair', 1332, 'She Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'puts hair in a ponytail', 1700, 'He Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'puts hair in a ponytail', 1705, 'She Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has comb-over hair', 1328, 'He Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has comb-over hair', 1328, 'She Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has short wavy hair', 1658, 'He Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has short wavy hair', 1329, 'She Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'has wavy hair', 1338, 'He Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'has wavy hair', 1321, 'She Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'puts hair in pigtails', 1714, 'He Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'puts hair in pigtails', 1715, 'She Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (1, 'is bald', 2290, 'He Name');
INSERT INTO hair(gender_id, name, value, idiomatic_answer) VALUES (2, 'is bald', 2290, 'She Name');
