INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (1, 'no', 1389,'He has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (2, 'no', 1407,'She has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (1, 'a normal', 1388,'He has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (2, 'a normal', 1406,'She has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (1, 'a angular', 1397,'He has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (2, 'a angular', 1415,'She has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (1, 'a big', 1403,'He has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (2, 'a big', 1421,'She has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (1, 'a small', 1391,'He has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (2, 'a small', 1409,'She has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (1, 'a broad', 1403,'He has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (2, 'a broad', 1421,'She has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (1, 'a narrow', 1391,'He has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (2, 'a narrow', 1409,'She has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (1, 'a long', 1400,'He has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (2, 'a long', 1418,'She has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (1, 'a short', 1391,'He has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (2, 'a short', 1409,'She has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (1, 'a firm', 1397,'He has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (2, 'a firm', 1415,'She has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (1, 'a sharp', 1394,'He has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (2, 'a sharp', 1413,'She has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (1, 'a protruding', 1390,'He has Name jaw');
INSERT INTO jaw(gender_id, name, value, idiomatic_answer) VALUES (2, 'a protruding', 1408,'She has Name jaw');