INSERT INTO mouth(gender_id, name, value, idiomatic_answer) VALUES (1, 'thin lips', 1437, 'He has Name');
INSERT INTO mouth(gender_id, name, value, idiomatic_answer) VALUES (2, 'thin lips', 2342, 'He has Name');
INSERT INTO mouth(gender_id, name, value, idiomatic_answer) VALUES (1, 'thick lips', 2339, 'He has Name');
INSERT INTO mouth(gender_id, name, value, idiomatic_answer) VALUES (2, 'thick lips', 2341, 'He has Name');
INSERT INTO mouth(gender_id, name, value, idiomatic_answer) VALUES (1, 'a big mouth', 2337, 'He has Name');
INSERT INTO mouth(gender_id, name, value, idiomatic_answer) VALUES (2, 'a big mouth', 2340, 'He has Name');
INSERT INTO mouth(gender_id, name, value, idiomatic_answer) VALUES (1, 'a small mouth', 2337, 'He has Name');
INSERT INTO mouth(gender_id, name, value, idiomatic_answer) VALUES (2, 'a small mouth', 2340, 'He has Name'); 
INSERT INTO mouth(gender_id, name, value, idiomatic_answer) VALUES (1, 'a normal mouth', 2337, 'He has Name');
INSERT INTO mouth(gender_id, name, value, idiomatic_answer) VALUES (2, 'a normal mouth', 2340, 'He has Name'); 