INSERT INTO question(context, question, gender_id) VALUES('gender', 'User, What is the gender of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('eye', 'User, What is the shape of the eyes of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('hair', 'User, How are the hair of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('nose', 'User, How is the nose of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('pupil_tone', 'User, What color are the eyes of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('mouth', 'User, How is the mouth of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('hair_tone', 'User, What color are the hair of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('beard', 'User, What color are the hair of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('brow', 'User, How are the brows of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('ear', 'User, How are the ear of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('eyelash', 'User, How are the eyelash of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('glasses', 'User, How are the glasses of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('jaw', 'User, How are the jaw of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('brow_tone', 'User, What color are the brow of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('beard_tone', 'User, What color are the beard of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('eyeshadow_tone', 'User, What color are the eyeshadow of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('lipstick_tone', 'User, What color are the lipstick of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('skin_tone', 'User, What color are the skin of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('gender', 'User, What is the gender of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('eye', 'User, What is the shape of the eyes of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('hair', 'User, How are the hair of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('nose', 'User, How is the nose of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('pupil_tone', 'User, What color are the eyes of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('mouth', 'User, How is the mouth of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('hair_tone', 'User, What color are the hair of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('brow', 'User, How are the brows of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('ear', 'User, How are the ear of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('eyelash', 'User, How are the eyelash of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('glasses', 'User, How are the glasses of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('jaw', 'User, How are the jaw of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('brow_tone', 'User, What color are the brow of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('eyeshadow_tone', 'User, What color are the eyeshadow of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('lipstick_tone', 'User, What color are the lipstick of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('skin_tone', 'User, What color are the skin of Described?',2);
