INSERT INTO question(context, question, gender_id) VALUES('gender', 'User, What is the gender of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('eye', 'User, What is the shape of the eyes of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('hair', 'User, How are the hair of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('nose', 'User, How is the nose of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('pupil_tone', 'User, What color are the eyes of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('mouth', 'User, How is the mouth of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('hair_tone', 'User, What color are the hair of Described?',1);
INSERT INTO question(context, question, gender_id) VALUES('gender', 'User, What is the gender of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('eye', 'User, What is the shape of the eyes of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('hair', 'User, How are the hair of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('nose', 'User, How is the nose of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('pupil_tone', 'User, What color are the eyes of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('mouth', 'User, How is the mouth of Described?',2);
INSERT INTO question(context, question, gender_id) VALUES('hair_tone', 'User, What color are the hair of Described?',2);