INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'grey', 12434877,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'grey', 12434877,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'blue', 1271190,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'blue', 1271190,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'green', 1482046,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'green', 1482046,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'olive', 13544297,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'olive', 13544297,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'orange', 15304521,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'orange', 15304521,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'purple', 7292807,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'purple', 7292807,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'red', 14429186,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'red', 14429186,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'yellow', 16240444,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'yellow', 16240444,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'white', 16772589,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'white', 16772589,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'ivory', 16765370,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'ivory', 16765370,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'beige', 16301209,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'beige', 16301209,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'light brown', 14324832,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'light brown', 14324832,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'brown', 9655597,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'brown', 9655597,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'dark brow,', 6174489,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'dark brow,', 6174489,'She has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (1, 'black', 5451546,'He has Name skin');
INSERT INTO skin_tone(gender_id, name, value, idiomatic_answer) VALUES (2, 'black', 5451546,'She has Name skin');